language: c
compiler:
  - gcc
# Change this to your needs
before_install: mkdir m4
install: aclocal && autoheader && autoreconf --install && automake --add-missing --copy
script: ./configure && make && make check
notifications:
  email:
    - arjenderijke@gmail.com
addons:
  apt:
    packages:
    - libmicrohttpd-dev
    - liburiparser-dev
    - libcunit1-dev
    - libcurl4-gnutls-dev
    