language: c
compiler:
  - gcc
# Change this to your needs
before_install: dpkg -l autoconf
install: autoheader && autoreconf --install && automake --add-missing --copy
script: ./configure && make && make check
notifications:
  email:
    - arjenderijke@gmail.com
